#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cmath>
#include <cstdlib>
#include <algorithm>
#include "OmniEngine.hpp"

// Simple helper to parse the specific JSON structure generated by Python
std::vector<float> extract_array(const std::string& data, const std::string& key, size_t start_pos, size_t& next_pos) {
    std::vector<float> res;
    size_t key_pos = data.find("\"" + key + "\"", start_pos);
    if (key_pos == std::string::npos) {
        next_pos = start_pos;
        return res;
    }
    
    size_t start = data.find('[', key_pos);
    if (start == std::string::npos) {
        next_pos = key_pos;
        return res;
    }
    size_t end = data.find(']', start);
    if (end == std::string::npos) {
        next_pos = start;
        return res;
    }
    
    std::string array_str = data.substr(start + 1, end - start - 1);
    std::stringstream ss(array_str);
    std::string val;
    while (std::getline(ss, val, ',')) {
        if (!val.empty()) {
            res.push_back(std::stof(val));
        }
    }
    next_pos = end;
    return res;
}

float extract_float(const std::string& data, const std::string& key, size_t start_pos, size_t& next_pos) {
    size_t key_pos = data.find("\"" + key + "\"", start_pos);
    if (key_pos == std::string::npos) {
        next_pos = start_pos;
        return 0.0f;
    }
    size_t colon = data.find(':', key_pos);
    if (colon == std::string::npos) {
        next_pos = key_pos;
        return 0.0f;
    }
    size_t comma = data.find(',', colon);
    if (comma == std::string::npos) {
        comma = data.find('}', colon);
    }
    std::string val = data.substr(colon + 1, comma - colon - 1);
    next_pos = comma;
    return std::stof(val);
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <parity_brain.omnibit> <reference_outputs.json>" << std::endl;
        return 1;
    }

    std::string omnibit_path = argv[1];
    std::string json_path = argv[2];

    // 1. Load the omnibit binary
    std::ifstream bin_file(omnibit_path, std::ios::binary | std::ios::ate);
    if (!bin_file.is_open()) {
        std::cerr << "Failed to open binary: " << omnibit_path << std::endl;
        return 1;
    }
    size_t bin_size = bin_file.tellg();
    bin_file.seekg(0, std::ios::beg);
    std::vector<unsigned char> omnibit_data(bin_size);
    if (!bin_file.read(reinterpret_cast<char*>(omnibit_data.data()), bin_size)) {
        std::cerr << "Failed to read binary file." << std::endl;
        return 1;
    }
    bin_file.close();

    // 2. Load the reference outputs JSON
    std::ifstream json_file(json_path);
    if (!json_file.is_open()) {
        std::cerr << "Failed to open reference outputs JSON: " << json_path << std::endl;
        return 1;
    }
    std::stringstream buffer;
    buffer << json_file.rdbuf();
    std::string json_data = buffer.str();
    json_file.close();

    // 3. Initialize C++ OmniEngine
    OmniEngine engine;
    if (!engine.Load(omnibit_data.data(), bin_size)) {
        std::cerr << "Failed to load omnibit in C++ OmniEngine!" << std::endl;
        return 1;
    }

    std::cout << "[C++ Parity] Model loaded successfully." << std::endl;
    std::cout << "  Input Dim:  " << engine.GetInputDim() << std::endl;
    std::cout << "  Model Dim:  " << engine.GetModelDim() << std::endl;
    std::cout << "  Output Dim: " << engine.GetOutputDim() << std::endl;

    // 4. Parse steps and run comparisons
    size_t search_pos = 0;
    int step_count = 0;
    float abs_time = 0.0f;
    float max_error = 0.0f;
    const float tolerance = 1e-3f;

    while (true) {
        size_t step_pos = json_data.find("\"step\"", search_pos);
        if (step_pos == std::string::npos) {
            break;
        }

        size_t next_pos = step_pos;
        int step_id = (int)extract_float(json_data, "step", step_pos, next_pos);
        std::vector<float> input = extract_array(json_data, "input", next_pos, next_pos);
        float dt = extract_float(json_data, "dt", next_pos, next_pos);
        std::vector<float> expected_action = extract_array(json_data, "action", next_pos, next_pos);
        std::vector<float> expected_state_out = extract_array(json_data, "state_out", next_pos, next_pos);

        if (input.empty()) {
            break;
        }

        // Run one inference step in C++
        std::vector<float> action = engine.Step(input.data(), dt, abs_time);
        abs_time += dt;

        // Check outputs
        std::cout << "Checking Step " << step_id << " (dt=" << dt << ", abs_time=" << abs_time << "):" << std::endl;
        
        // Output dim should match
        if (action.size() != expected_action.size()) {
            std::cerr << "  ❌ Dimension mismatch on step " << step_id 
                      << ". Got " << action.size() << ", expected " << expected_action.size() << std::endl;
            return 1;
        }

        // Numerical comparison
        for (size_t i = 0; i < action.size(); ++i) {
            float err = std::abs(action[i] - expected_action[i]);
            max_error = std::max(max_error, err);
            if (err > tolerance) {
                std::cerr << "  ❌ Parity mismatch on step " << step_id << ", output index " << i 
                          << ". Got " << action[i] << ", expected " << expected_action[i] 
                          << " (error = " << err << ", tolerance = " << tolerance << ")" << std::endl;
                return 1;
            }
        }
        std::cout << "  ✅ Passed (max error: " << max_error << ")" << std::endl;

        search_pos = next_pos;
        step_count++;
    }

    if (step_count == 0) {
        std::cerr << "❌ Error: No steps were parsed from the reference JSON!" << std::endl;
        return 1;
    }

    std::cout << "\n==============================================" << std::endl;
    std::cout << "🎉 SUCCESS: C++ and Python models are numerical duplicates!" << std::endl;
    std::cout << "  Total steps verified: " << step_count << std::endl;
    std::cout << "  Absolute Max Error:   " << max_error << std::endl;
    std::cout << "==============================================" << std::endl;

    return 0;
}
