[build-system]
requires = ["setuptools>=42", "wheel", "pybind11>=2.6"]
build-backend = "setuptools.build_meta"

[project]
name = "omnitrain"
version = "1.2.0"
description = "Multimodal AI Framework for Robotics"
readme = "README.md"
dependencies = [
    "numpy",
    "torch",
    "rich",
    "pyyaml",
    "prompt_toolkit>=3.0",
    "pydantic",
    "pyserial"
]

[tool.setuptools.packages.find]
where = ["src"]
