#ifndef OMNI_HAL_HPP
#define OMNI_HAL_HPP

// ============================================================
// OmniHAL: STM32 Hardware Abstraction Layer
// ============================================================
// Strategy: LINKER-EMBEDDED ZERO-COPY via objcopy C-array.
// On STM32, the most robust way to store a binary blob in Flash
// is to convert the .omnibit file into a C array at compile time
// and link it directly into the .rodata Flash section.
//
// Step 1 (One-time, offline on your PC):
//   arm-none-eabi-objcopy -I binary -O elf32-littlearm \
//     --rename-section .data=.rodata,alloc,load,readonly,data,contents \
//     bot_brain.omnibit bot_brain.o
//
// Step 2: Add bot_brain.o to your CMakeLists.txt or Makefile.
//
// Step 3: Declare the linker symbols below (already done here).
//
// Toolchain: STM32CubeIDE / PlatformIO (ststm32)
// ============================================================

#include <cstddef>
#include <cstdint>

struct OmniHALResult {
    const unsigned char* data;
    size_t               length;
    bool                 ok;
};

// These symbols are automatically generated by arm-none-eabi-objcopy.
// They point directly to the .omnibit data embedded in Flash (.rodata section).
extern "C" {
    extern const uint8_t _binary_bot_brain_omnibit_start[];
    extern const uint8_t _binary_bot_brain_omnibit_end[];
}

inline OmniHALResult OmniHAL_LoadBrain() {
    OmniHALResult result = {nullptr, 0, false};

    const unsigned char* data   = _binary_bot_brain_omnibit_start;
    size_t               length = (size_t)(_binary_bot_brain_omnibit_end -
                                            _binary_bot_brain_omnibit_start);

    if (length < 28) {
        return result; // Not a valid .omnibit file
    }

    // True Zero-Copy: The pointer IS the Flash address.
    // The STM32's Cortex-M core reads directly from the AHB bus connected to Flash.
    result.data   = data;
    result.length = length;
    result.ok     = true;
    return result;
}

#endif // OMNI_HAL_HPP
