import struct
import torch
import torch.nn as nn
from pathlib import Path
import yaml

class ESP32Exporter:
    """
    Omnitrain to ESP32 binary (.omnibit) exporter.
    Exports network weights into a continuous blob for Zero-Copy access from Flash memory (DROM).
    Includes structured extraction for exact CfC math and OmniShield validation.
    """
    def __init__(self, output_dir="exports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.magic = b'OMNI\x02' # Version 2: Structured Layout
        
    def export(self, model: nn.Module, input_dim: int, d_model: int, output_dim: int, 
               backbone_units: int = 128, config_path: str = None, filename: str = "bot_brain.omnibit"):
        out_path = self.output_dir / filename
        weights = []
        
        print("[ESP32Exporter] Extracting weights for Zero-Copy export (V2 Structured)...")
        
        def push_tensor(t):
            weights.extend(t.detach().cpu().numpy().flatten().tolist())

        # 1. Input Projector
        if hasattr(model, 'input_projector'):
            proj = model.input_projector.default_proj
            push_tensor(proj.weight)
            push_tensor(proj.bias)
            
        # 2. Continuous Temporal Encoding (CTE)
        if hasattr(model, 'temporal_encoder'):
            cte = model.temporal_encoder
            push_tensor(cte.inv_freq)
            push_tensor(cte.amplitude)
            push_tensor(cte.phase)
            
        # 3. BioLiquidCell (Explicit extraction for C++ engine mapping)
        # Assuming mode="default" and backbone_layers=1
        if hasattr(model, 'brain'):
            brain = model.brain
            if hasattr(brain, 'sensory_w'):
                push_tensor(brain.sensory_w)
                push_tensor(brain.sensory_b)
                
                # Backbone State (Linear 0)
                state_lin = brain.backbone_state[0]
                push_tensor(state_lin.weight)
                push_tensor(state_lin.bias)
                
                # Backbone Time (Linear 0)
                time_lin = brain.backbone_time[0]
                push_tensor(time_lin.weight)
                push_tensor(time_lin.bias)
                
                # FF1 & FF2
                push_tensor(brain.ff1.weight)
                push_tensor(brain.ff1.bias)
                push_tensor(brain.ff2.weight)
                push_tensor(brain.ff2.bias)
                
                # Time Gates
                push_tensor(brain.time_a.weight)
                push_tensor(brain.time_a.bias)
                push_tensor(brain.time_b.weight)
                push_tensor(brain.time_b.bias)
                
                # Time Scale
                push_tensor(brain.time_scale)

        # 4. TODO: Add Regressor and OmniShield export

        # Save to Binary Format (.omnibit)
        with open(out_path, "wb") as f:
            # Magic + Padding (3 bytes) to ensure 4-byte float offset alignment
            f.write(self.magic + b'\x00\x00\x00') 
            
            # Dimensions Header (20 bytes)
            # Layout: input_dim, d_model, output_dim, backbone_units, len(weights)
            # Current Offset: 8 bytes. After 20 bytes -> Float Offset: 28 bytes (multiple of 4)
            f.write(struct.pack('<IIIII', input_dim, d_model, output_dim, backbone_units, len(weights)))
            
            # Weights array
            if len(weights) > 0:
                f.write(struct.pack(f'<{len(weights)}f', *weights))
            
        print(f"[ESP32Exporter] Successfully exported to {out_path}")
        size_kb = out_path.stat().st_size / 1024.0
        print(f"[ESP32Exporter] Flash footprint: {size_kb:.2f} KB ({len(weights)} parameters)")
        
        if config_path:
            self._export_hw_config(config_path, self.output_dir / "esp32_hw_config.h")

    def _export_hw_config(self, yaml_path, out_header):
        yaml_file = Path(yaml_path)
        if not yaml_file.exists():
            return
            
        with open(yaml_file, 'r') as f:
            config = yaml.safe_load(f)
            
        hw = config.get('hardware', {}).get('esp32', {})
        if not hw:
            return
            
        with open(out_header, 'w') as f:
            f.write("#ifndef ESP32_HW_CONFIG_H\n")
            f.write("#define ESP32_HW_CONFIG_H\n\n")
            f.write("// Auto-generated by Omnitrain ESP32Exporter\n\n")
            for key, val in hw.items():
                macro = key.upper()
                f.write(f"#define HW_{macro} {val}\n")
            f.write("\n#endif // ESP32_HW_CONFIG_H\n")
