name=OmniTrainEngine
version=1.0.0
author=Manuel Yobani Martinez Sanchez (Mr.Myms)
maintainer=Manuel Yobani Martinez Sanchez (Mr.Myms)
sentence=Bare-Metal Neural Inference Engine for ESP32 and microcontrollers.
paragraph=OmniTrainEngine allows you to dynamically load and run Neural Networks (LSTM, GRU, Dense CfC, Sparse CfC) efficiently on microcontrollers without operating systems. Features dynamically allocated memory buffers and native 32-bit floating point hardware acceleration.
category=Data Processing
url=https://github.com/mr-myms/OmniTrain
architectures=*
