import sys
import os

input_file = "/Users/mr.myms/Omnitrain/paper_experiments/data/f110_reflex_rl_champion.omnibit"
output_file = "/Users/mr.myms/Omnitrain/hil_test/include/model.h"

with open(input_file, "rb") as f:
    data = f.read()

with open(output_file, "w") as f:
    f.write("// Auto-generated by Omnitrain ESP32Exporter (F1TENTH Champion)\n")
    f.write(f"// Flash footprint: {len(data)/1024:.2f} KB\n")
    f.write("#ifndef HIL_MODEL_OMNIBIT_H\n")
    f.write("#define HIL_MODEL_OMNIBIT_H\n\n")
    f.write("#include <stddef.h>\n\n")
    f.write("const unsigned char __attribute__((aligned(4))) hil_model_omnibit[] = {\n    ")
    for i, byte in enumerate(data):
        f.write(f"0x{byte:02x}, ")
        if (i+1) % 12 == 0:
            f.write("\n    ")
    f.write("\n};\n")
    f.write(f"const size_t hil_model_omnibit_len = {len(data)};\n")
    f.write("#endif\n")
print(f"Exported {len(data)} bytes to {output_file}")
